name: cm_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9.0
  - igl=2.2.1
  - matplotlib=3.4.2
  - tqdm=4.62.2
  - mpmath=1.2.1
  - meshplot=0.4.0
  - multipledispatch=0.6.0
  - pandas=1.3.4
